# Try Catch

#### 程序抛出异常时，是如何寻找处理代码的呢？

寻找处理代码的过程与函数调用链刚好相反。

当异常被抛出时，

1. 首先搜索抛出该异常的函数中是否有匹配的catch语句。
2. 如果没有，终止该函数并在调用该函数的函数中寻找。
3. 如果也没有，终止调用该函数的函数。继续搜索调用它的函数。
4. 以此类推，沿着程序的执行路径逐层回退，直到找到适当类型的catch子句。
5. 如果最终没能找到匹配的catch子句，程序会转到terminate的标准库函数（该函数的行为与系统有关，一般情况下，执行该函数将导致程序非正常退出）。
6. 如果程序中没有try语句且发生了异常，系统会调用terminate函数并终止当前程序的执行。

> 异常中断了程序的正常流程。异常发生时，调用者请求的一部分计算已经完成，另一部分没有完成。略过部分程序就有可能使得对象处于无效或者未完成的状态，资源没有正常释放等。异常发生期间执行**清理**工作的程序就是**异常安全（exception safe）**的代码。这种代码非常难编写…